steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'
      - './backend'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '15m'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-secrets'
      - 'AIRTABLE_PAT=AIRTABLE_PAT:latest,AT_STUDENTS_BASE=AT_STUDENTS_BASE:latest,AT_STUDENTS_TABLE=AT_STUDENTS_TABLE:latest,AT_PARENTS_BASE=AT_PARENTS_BASE:latest,AT_PARENTS_TABLE=AT_PARENTS_TABLE:latest,AT_CONTRACTORS_BASE=AT_CONTRACTORS_BASE:latest,AT_CONTRACTORS_TABLE=AT_CONTRACTORS_TABLE:latest,AT_CLASSES_BASE=AT_CLASSES_BASE:latest,AT_CLASSES_TABLE=AT_CLASSES_TABLE:latest,AT_ATTENDANCE_BASE=AT_ATTENDANCE_BASE:latest,AT_ATTENDANCE_TABLE=AT_ATTENDANCE_TABLE:latest,AT_TRUTH_BASE=AT_TRUTH_BASE:latest,AT_TRUTH_TABLE=AT_TRUTH_TABLE:latest,AT_PAYMENTS_BASE=AT_PAYMENTS_BASE:latest,AT_PAYMENTS_TABLE=AT_PAYMENTS_TABLE:latest,GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS:latest'

substitutions:
  _REGION: us-central1
  _ARTIFACT_REGISTRY: integrity-monitor
  _SERVICE_NAME: integrity-runner
  _SERVICE_ACCOUNT: integrity-runner@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'

